# -*- coding: utf-8 -*-

from brian2 import *
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np

VPY_3 = np.loadtxt('../../Data/PY_v_disconnectedfromthalamus.txt')
VPY_2 = np.loadtxt('../../Data/PY_v_disconnectedfromthalamus_N60.txt')
VPY_1 = np.loadtxt('../../Data/PY_v_disconnectedfromthalamus_N20.txt')
VPY_4 = np.loadtxt('../../Data/PY_v_disconnectedfromthalamus_Mini120.txt')
VPY_5 = np.loadtxt('../../Data/PY_v_disconnectedfromthalamus_Mini140.txt')
VPY_6 = np.loadtxt('../../Data/PY_v_disconnectedfromthalamus_Mini170.txt')
time = np.loadtxt('../../Data/time_20.txt')

###Figure 10
fig,ax = subplots(3,1, sharex = True,figsize=(15,15))
ax[0].plot(time/1000, VPY_1,color="tab:blue",linewidth=1.5)
ax[0].set_title('PY, N=20', size=35, loc='left')
ax[0].set_ylabel('mV',size=30, labelpad=25)
ax[0].spines['top'].set_visible(False)
ax[0].spines['right'].set_visible(False)
ax[0].spines['bottom'].set_visible(True)
ax[0].spines['left'].set_visible(True)
ax[0].yaxis.set_major_locator(MultipleLocator(base=25))
ax[0].set_xlim([0,8])
ax[0].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[1].plot(time/1000, VPY_2,color="tab:blue",linewidth=1.5)
ax[1].set_title('PY, N=60', size=35, loc='left')
ax[1].set_ylabel('mV',size=30, labelpad=25)
ax[1].spines['top'].set_visible(False)
ax[1].spines['right'].set_visible(False)
ax[1].spines['bottom'].set_visible(True)
ax[1].spines['left'].set_visible(True)
ax[1].yaxis.set_major_locator(MultipleLocator(base=25))
ax[1].set_xlim([0,8])
ax[1].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[2].plot(time/1000, VPY_3,color="tab:blue",linewidth=1.5)
ax[2].set_title('PY, N=100', size=35, loc='left')
ax[2].set_ylabel('mV',size=30, labelpad=25)
ax[2].set_xlabel('Time (s)',size=30, labelpad=25)
ax[2].spines['top'].set_visible(False)
ax[2].spines['right'].set_visible(False)
ax[2].spines['bottom'].set_visible(True)
ax[2].spines['left'].set_visible(True)
ax[2].yaxis.set_major_locator(MultipleLocator(base=25))
ax[2].set_xlim([0,8])
ax[2].tick_params(axis='both', which='major', labelsize=30, width=2)
plt.savefig('Figure10Apy.png', dpi=300, bbox_inches='tight')

fig,ax = subplots(3,1, sharex = True,figsize=(15,15))
ax[0].plot(time/1000, VPY_4,color="tab:blue",linewidth=1.5)
ax[0].set_title('PY, 120% mini amplitude', size=35, loc='left')
ax[0].set_ylabel('mV',size=30, labelpad=25)
ax[0].spines['top'].set_visible(False)
ax[0].spines['right'].set_visible(False)
ax[0].spines['bottom'].set_visible(True)
ax[0].spines['left'].set_visible(True)
ax[0].yaxis.set_major_locator(MultipleLocator(base=25))
ax[0].set_xlim([0,8])
ax[0].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[1].plot(time/1000, VPY_5,color="tab:blue",linewidth=1.5)
ax[1].set_title('PY, 140% mini amplitude', size=35, loc='left')
ax[1].set_ylabel('mV',size=30, labelpad=25)
ax[1].spines['top'].set_visible(False)
ax[1].spines['right'].set_visible(False)
ax[1].spines['bottom'].set_visible(True)
ax[1].spines['left'].set_visible(True)
ax[1].yaxis.set_major_locator(MultipleLocator(base=25))
ax[1].set_xlim([0,8])
ax[1].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[2].plot(time/1000, VPY_6,color="tab:blue",linewidth=1.5)
ax[2].set_title('PY, 170% mini amplitude', size=35, loc='left')
ax[2].set_ylabel('mV',size=30, labelpad=25)
ax[2].set_xlabel('Time (s)',size=30, labelpad=25)
ax[2].spines['top'].set_visible(False)
ax[2].spines['right'].set_visible(False)
ax[2].spines['bottom'].set_visible(True)
ax[2].spines['left'].set_visible(True)
ax[2].yaxis.set_major_locator(MultipleLocator(base=25))
ax[2].set_xlim([0,8])
ax[2].tick_params(axis='both', which='major', labelsize=30, width=2)
plt.savefig('Figure10Bpy.png', dpi=300, bbox_inches='tight')