# -*- coding: utf-8 -*-
"""
Created on Tue Aug  6 11:56:29 2024

@author: Mathilde
"""

###Figure 8 
#top
fig,ax = subplots(4,1, sharex = True,figsize=(19,18))
ax[0].plot(V2_PYs.t/second, V2_PYs.v[N//2]/mV,color="tab:blue",linewidth=1.5)
ax[0].set_title('PY', size=30, loc='left')
ax[0].set_ylabel('mV',size=30, labelpad=30)
ax[0].set_xlim([15,30])
ax[0].spines['top'].set_visible(False)
ax[0].spines['right'].set_visible(False)
ax[0].spines['bottom'].set_visible(True)
ax[0].spines['left'].set_visible(True)
ax[0].yaxis.set_major_locator(MultipleLocator(base=25))
ax[0].tick_params(axis='both', which='major', labelsize=25, width=2)
#
ax[1].plot(V4_INs.t/second, V4_INs.v[int(N_IN//2)]/mV,color="tab:green",linewidth=1.5)
ax[1].set_title('IN', size=30, loc='left')
ax[1].set_ylabel('mV',size=30, labelpad=30)
ax[1].spines['top'].set_visible(False)
ax[1].spines['right'].set_visible(False)
ax[1].spines['bottom'].set_visible(True)
ax[1].spines['left'].set_visible(True)
ax[1].yaxis.set_major_locator(MultipleLocator(base=25))
ax[1].tick_params(axis='both', which='major', labelsize=25, width=2)
#
ax[2].plot(V1_RE_TCo.t/second, V1_RE_TCo.v[20]/mV,color="tab:red",linewidth=1.5)
ax[2].set_title('RE', size=30, loc='left')
ax[2].set_ylabel('mV',size=30, labelpad=30)
ax[2].spines['top'].set_visible(False)
ax[2].spines['right'].set_visible(False)
ax[2].spines['bottom'].set_visible(True)
ax[2].spines['left'].set_visible(True)
ax[2].yaxis.set_major_locator(MultipleLocator(base=25))
ax[2].tick_params(axis='both', which='major', labelsize=25, width=2)
#
ax[3].plot(V2_TC_TCo.t/second, V2_TC_TCo.v[20]/mV,color="tab:orange",linewidth=1.5)
ax[3].set_title('TC', size=30, loc='left')
ax[3].set_ylabel('mV', size=30, labelpad=30)
ax[3].set_xlabel('second', size=30)
ax[3].tick_params(axis='both',labelbottom=True)
ax[3].spines['top'].set_visible(False)
ax[3].spines['right'].set_visible(False)
ax[3].spines['bottom'].set_visible(True)
ax[3].spines['left'].set_visible(True)
ax[3].yaxis.set_major_locator(MultipleLocator(base=25))
ax[3].tick_params(axis='both', which='major', labelsize=25, width=2)
#plt.savefig('Figure8top.png', dpi=300)
#bottom
fig,ax = subplots(4,1, sharex = True,figsize=(19,18))
#
ax[0].plot(V2_PYs.t/ms, V2_PYs.v[50]/mV,color="tab:blue",linewidth=1.5)
ax[0].axhline(y=-68, color='gray', linestyle='--', linewidth=1.5)
ax[0].text(10000, -66, '-68 mV', color='gray', fontsize=30,verticalalignment='bottom', horizontalalignment='right')
ax[0].set_title('PY', size=30, loc='left')
ax[0].set_ylabel('mV',size=30, labelpad=30)
ax[0].set_xlim([9600,12100])
ax[0].spines['top'].set_visible(False)
ax[0].spines['right'].set_visible(False)
ax[0].spines['bottom'].set_visible(True)
ax[0].spines['left'].set_visible(True)
ax[0].yaxis.set_major_locator(MultipleLocator(base=25))
ax[0].tick_params(axis='both', which='major', labelsize=25, width=2)
#
ax[1].plot(V4_INs.t/ms, V4_INs.v[12]/mV,color="tab:green",linewidth=1.5)
ax[1].text(10000, -64, '-66 mV', color='gray', fontsize=30,verticalalignment='bottom', horizontalalignment='right')
ax[1].axhline(y=-66, color='gray', linestyle='--', linewidth=1.5)
ax[1].set_title('IN', size=30, loc='left')
ax[1].set_ylabel('mV',size=30, labelpad=30)
ax[1].set_xlim([9600,12100])
ax[1].spines['top'].set_visible(False)
ax[1].spines['right'].set_visible(False)
ax[1].spines['bottom'].set_visible(True)
ax[1].spines['left'].set_visible(True)
ax[1].yaxis.set_major_locator(MultipleLocator(base=25))
ax[1].tick_params(axis='both', which='major', labelsize=25, width=2)
#
ax[2].plot(V1_RE_TCo.t/ms, V1_RE_TCo.v[20]/mV,color="tab:red",linewidth=1.5)
ax[2].text(10000, -71, '-73 mV', color='gray', fontsize=30,verticalalignment='bottom', horizontalalignment='right')
ax[2].axhline(y=-73, color='gray', linestyle='--', linewidth=1.5)
ax[2].set_title('RE', size=30, loc='left')
ax[2].set_ylabel('mV',size=30, labelpad=30)
ax[2].set_xlim([9600,12100])
ax[2].spines['top'].set_visible(False)
ax[2].spines['right'].set_visible(False)
ax[2].spines['bottom'].set_visible(True)
ax[2].spines['left'].set_visible(True)
ax[2].yaxis.set_major_locator(MultipleLocator(base=25))
ax[2].tick_params(axis='both', which='major', labelsize=25, width=2)
#
ax[3].plot(V2_TC_TCo.t/ms, V2_TC_TCo.v[20]/mV,color="tab:orange",linewidth=1.5)
ax[3].text(10000, -70, '-72 mV', color='gray', fontsize=30,verticalalignment='bottom', horizontalalignment='right')
ax[3].axhline(y=-72, color='gray', linestyle='--', linewidth=1.5)
ax[3].set_title('TC', size=30, loc='left')
ax[3].set_ylabel('mV',size=30, labelpad=30)
ax[3].set_xlabel('ms', size=30)
ax[3].set_xlim([9600,12100])
ax[3].spines['top'].set_visible(False)
ax[3].spines['right'].set_visible(False)
ax[3].spines['bottom'].set_visible(True)
ax[3].spines['left'].set_visible(True)
ax[3].yaxis.set_major_locator(MultipleLocator(base=25))
ax[3].tick_params(axis='both', which='major', labelsize=25, width=2)
#plt.savefig('Figure8bottom.png', dpi=300)