# -*- coding: utf-8 -*-

from brian2 import *
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np

#Make sure your working directory is properly set to access the .txt
VPY_1 = np.loadtxt('PY_v_withoutkleak_strong.txt')
VRE_1 = np.loadtxt('RE_v_withoutkleak_strong.txt')
VTC_1 = np.loadtxt('TC_v_withoutkleak_strong.txt')

VPY_2 = np.loadtxt('PY_v_withoutkleak_weakPY.txt')
VRE_2 = np.loadtxt('RE_v_withoutkleak_weakPY.txt')
VTC_2 = np.loadtxt('TC_v_withoutkleak_weakPY.txt')

VPY_3 = np.loadtxt('PY_v_withoutkleak_weakPYRETC.txt')
VRE_3 = np.loadtxt('RE_v_withoutkleak_weakPYRETC.txt')
VTC_3 = np.loadtxt('TC_v_withoutkleak_weakPYRETC.txt')

time = np.loadtxt('time_10.txt')

#For firing frequency measures see the file FiringFrequency.ods
gPYPY=[0.08,0.10,0.12,0.14,0.16]
freqPY=[11.8065,14.361,18.634,21.5795,25.9875]

###Figure 11 top
fig,ax = subplots(3,1, sharex = True,figsize=(12,15))
ax[0].plot(time/1000, VPY_1,color="tab:blue",linewidth=1.5)
ax[0].set_title('PY, strong PY-PY', size=35, loc='left')
ax[0].set_ylabel('mV',size=30, labelpad=25)
ax[0].spines['top'].set_visible(False)
ax[0].spines['right'].set_visible(False)
ax[0].spines['bottom'].set_visible(True)
ax[0].spines['left'].set_visible(True)
ax[0].yaxis.set_major_locator(MultipleLocator(base=25))
ax[0].set_xlim([7,10])
ax[0].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[1].plot(time/1000, VRE_1,color="tab:red",linewidth=1.5)
ax[1].set_title('RE, strong PY-PY', size=35, loc='left')
ax[1].set_ylabel('mV',size=30, labelpad=25)
ax[1].spines['top'].set_visible(False)
ax[1].spines['right'].set_visible(False)
ax[1].spines['bottom'].set_visible(True)
ax[1].spines['left'].set_visible(True)
ax[1].yaxis.set_major_locator(MultipleLocator(base=25))
ax[1].set_xlim([7,10])
ax[1].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[2].plot(time/1000, VTC_1,color="tab:orange",linewidth=1.5)
ax[2].set_title('TC, strong PY-PY', size=35, loc='left')
ax[2].set_ylabel('mV',size=30, labelpad=25)
ax[2].set_xlabel('Time (s)',size=30, labelpad=25)
ax[2].spines['top'].set_visible(False)
ax[2].spines['right'].set_visible(False)
ax[2].spines['bottom'].set_visible(True)
ax[2].spines['left'].set_visible(True)
ax[2].yaxis.set_major_locator(MultipleLocator(base=25))
ax[2].set_xlim([7,10])
ax[2].tick_params(axis='both', which='major', labelsize=30, width=2)
#plt.savefig('Figure16strongPYPY.png', dpi=300, bbox_inches='tight')
#
fig,ax = subplots(3,1, sharex = True,figsize=(12,15))
ax[0].plot(time/1000, VPY_2,color="tab:blue",linewidth=1.5)
ax[0].set_title('PY, weak PY-PY', size=35, loc='left')
ax[0].set_ylabel('mV',size=30, labelpad=25)
ax[0].spines['top'].set_visible(False)
ax[0].spines['right'].set_visible(False)
ax[0].spines['bottom'].set_visible(True)
ax[0].spines['left'].set_visible(True)
ax[0].yaxis.set_major_locator(MultipleLocator(base=25))
ax[0].set_xlim([7,10])
ax[0].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[1].plot(time/1000, VRE_2,color="tab:red",linewidth=1.5)
ax[1].set_title('RE, weak PY-PY', size=35, loc='left')
ax[1].set_ylabel('mV',size=30, labelpad=25)
ax[1].spines['top'].set_visible(False)
ax[1].spines['right'].set_visible(False)
ax[1].spines['bottom'].set_visible(True)
ax[1].spines['left'].set_visible(True)
ax[1].yaxis.set_major_locator(MultipleLocator(base=25))
ax[1].set_xlim([7,10])
ax[1].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[2].plot(time/1000, VTC_2,color="tab:orange",linewidth=1.5)
ax[2].set_title('TC, weak PY-PY', size=35, loc='left')
ax[2].set_ylabel('mV',size=30, labelpad=25)
ax[2].set_xlabel('Time (s)',size=30, labelpad=25)
ax[2].spines['top'].set_visible(False)
ax[2].spines['right'].set_visible(False)
ax[2].spines['bottom'].set_visible(True)
ax[2].spines['left'].set_visible(True)
ax[2].yaxis.set_major_locator(MultipleLocator(base=25))
ax[2].set_xlim([7,10])
ax[2].tick_params(axis='both', which='major', labelsize=30, width=2)
#plt.savefig('Figure16weakPYPY.png', dpi=300, bbox_inches='tight')
#
fig,ax = subplots(3,1, sharex = True,figsize=(12,15))
ax[0].plot(time/1000, VPY_3,color="tab:blue",linewidth=1.5)
ax[0].set_title('PY, weak PY-PY & RE-TC-RE', size=35, loc='left')
ax[0].set_ylabel('mV',size=30, labelpad=25)
ax[0].spines['top'].set_visible(False)
ax[0].spines['right'].set_visible(False)
ax[0].spines['bottom'].set_visible(True)
ax[0].spines['left'].set_visible(True)
ax[0].yaxis.set_major_locator(MultipleLocator(base=25))
ax[0].set_xlim([7,10])
ax[0].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[1].plot(time/1000, VRE_3,color="tab:red",linewidth=1.5)
ax[1].set_title('RE, weak PY-PY & RE-TC-RE', size=35, loc='left')
ax[1].set_ylabel('mV',size=30, labelpad=25)
ax[1].spines['top'].set_visible(False)
ax[1].spines['right'].set_visible(False)
ax[1].spines['bottom'].set_visible(True)
ax[1].spines['left'].set_visible(True)
ax[1].yaxis.set_major_locator(MultipleLocator(base=25))
ax[1].set_xlim([7,10])
ax[1].tick_params(axis='both', which='major', labelsize=30, width=2)
ax[2].plot(time/1000, VTC_3,color="tab:orange",linewidth=1.5)
ax[2].set_title('TC, weak PY-PY & RE-TC-RE', size=35, loc='left')
ax[2].set_ylabel('mV',size=30, labelpad=25)
ax[2].set_xlabel('Time (s)',size=30, labelpad=25)
ax[2].spines['top'].set_visible(False)
ax[2].spines['right'].set_visible(False)
ax[2].spines['bottom'].set_visible(True)
ax[2].spines['left'].set_visible(True)
ax[2].yaxis.set_major_locator(MultipleLocator(base=25))
ax[2].set_xlim([7,10])
ax[2].tick_params(axis='both', which='major', labelsize=30, width=2)
#plt.savefig('Figure16weakPYPYRETC.png', dpi=300, bbox_inches='tight')

###Figure 11 bottom
plt.figure(figsize=(7, 6))
plt.plot(gPYPY, freqPY, marker='^', color="black")
plt.xlabel('Conductance PY-PY $(μS)$', size=30, labelpad=20)
plt.ylabel('Frequency (Hz)', size=30, labelpad=20)
ax = plt.gca()
ax.yaxis.set_label_position("right")
ax.yaxis.tick_right()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(True)
ax.spines['left'].set_visible(False)
ax.spines['bottom'].set_visible(True)
plt.tick_params(axis='both', which='major', labelsize=30, width=2)
plt.savefig('Figure16bottom.png', dpi=300, bbox_inches='tight')
plt.show()
